apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: healthcare-eks
  region: us-east-1
  version: "1.31"

availabilityZones: ["us-east-1a", "us-east-1b"]

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

managedNodeGroups:
  - name: ng-healthcare
    instanceType: t2.micro # Updated: Forced to use a Free Tier eligible instance type
    desiredCapacity: 2
    volumeSize: 20
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
